### ISSUE TITLE
US 05.03.01 - Driver Notifications

### ISSUE THREAD

**Issue by dijonron** [CMPUT301W20T12/GufyGuber#15]
[US 05.03.01](https://github.com/CMPUT301W20T12/GufyGuber/wiki/User-Stories#us-050301)
When there is a ride request that both a rider and driver have agreed to, the driver involved should receive a notification.

**Comment by rmacgill** [comment]
Note that this issue and the "Rider Notifications" issue will likely share a lot of the same underlying functionality. As such, they should be worked on in tandem by the same team member(s), and the story-point value reflects both issues together.
