### ISSUE TITLE
Driver map screen does not need CreateRideRequest FAB

### ISSUE THREAD

**Issue by dijonron** [CMPUT301W20T12/GufyGuber#34]
Driver's aren't making ride requests, so there is no need for the FAB when a driver is logged in. Should be a simple fix to just set the visibility to GONE based on the user type, unless someone has another solution

**Comment by Robert-MacGillivray** [comment]
The FAB is built by the map fragment, and we'll have to modify the map fragment (or just build a new one) that works for drivers being able to see ride requests anyway. Could probably bundle this up with that and not build the FAB when we're making a map for drivers.
