### ISSUE TITLE
Email not updating in firebase

### ISSUE THREAD

**Issue by dijonron** [CMPUT301W20T12/GufyGuber#35]
Updating user email will change in "users" collection in firestore, but will not change the email associated with the authenticated firestore UID

**Comment by dijonron** [comment]
might have to delete the current gmail authentication account, and authenticate the new updated email

**Comment by dijonron** [comment]
would need to update the UID then as well

**Comment by rmacgill** [comment]
I think @hmp31 had mentioned researching a solution for this that would maintain the UID (which is kind of essential since all of our records are keyed with the UID).

**Comment by hmp31** [comment]
I don't know if we have the option to explicitly set the uid for the user with google sign in like we did with the normal email/password (I still need to confirm this).

**Comment by dijonron** [comment]
The more I look into it, it seems like we cannot just update the email for Google Auth user. Firebase gets authorization credentials for the GoogleSignInClient, so I think we would have to repeat this step and make a new account and sync up the new UID with all the other data on the user. I'm also not sure if we can just pass the gmail string to do this, or if we would need to utilize the whole google account selector fragment again to get all the credentials. Unless you were able to find another way @hmp31 ?

Either way, I'm going to update the SP on this.

**Comment by hmp31** [comment]
I don't believe we have a problem here. Updating the email does indeed change the email associated with both the authentication account and the user table, at least from my build. I was able to sign in with one account, verify my credentials on firebase, change my email, verify my new credentials on firebase and sign in with the other account.
