### ISSUE TITLE
Driver Menus are Innapropriate

### ISSUE THREAD

**Issue by rmacgill** [CMPUT301W20T12/GufyGuber#47]
The only items that work in the driver menu are the additional test items and the map view. We need a different layout when the driver looks at their currently accepted request, and we need a menu for reviewing and editing their vehicle information. Related to #45.

**Comment by dijonron** [comment]
Driver's now have a unique edit profile screen to update their profile info and vehicle info. I'll keep looking into the current requests, but that likely won't be implemented by the project 3 deadline.
