### ISSUE TITLE
US 01.03.01 - Rider Notifications

### ISSUE THREAD

**Issue by dijonron** [CMPUT301W20T12/GufyGuber#6]
[US 01.03.01](https://github.com/CMPUT301W20T12/GufyGuber/wiki/User-Stories#us-010301)
Rider is notified when their open ride request is accepted.

**Comment by dijonron** [comment]
Does notification only appear if app is open, or does user receive it as a background notification too>

**Comment by rmacgill** [comment]
Note that this issue and the "Driver Notifications" issue will likely share a lot of the same underlying functionality. As such, they should be worked on in tandem by the same team member(s), and the story-point value reflects both issues together.
