### ISSUE TITLE
US 04.01.01 Geo-location Request Search

### ISSUE THREAD

**Issue by hmp31** [CMPUT301W20T12/GufyGuber#7]
[US 04.01.01](https://github.com/CMPUT301W20T12/GufyGuber/wiki/User-Stories#us-040101)
Driver can search for open requests by geo-location.

**Comment by Djohnronan** [comment]
Also incorporates US 07.02.01

**Comment by rmacgill** [comment]
I wonder if we need to support this via the map, or some sort of location-based search.
