### ISSUE TITLE
Signed in as: XXX doesn't match profile information

### ISSUE THREAD

**Issue by rmacgill** [CMPUT301W20T12/GufyGuber#72]
The "Signed in as: XXX" text on the title screen uses a name that doesn't match your Gufy Guber profile (seems like it's pulling that name straight from Google). Maybe just display the email instead?

**Comment by dijonron** [comment]
Updated it to display the email. I think we could use updateDisplayName() when they edit the profile if we want the name still, but I think the email is fine
