### ISSUE TITLE
US 06.01.01 - Offline Request View (Driver)

### ISSUE THREAD

**Issue by hmp31** [CMPUT301W20T12/GufyGuber#9]
[US 06.01.01](https://github.com/CMPUT301W20T12/GufyGuber/wiki/User-Stories#us-060101)
Driver can view requests that they have accepted while offline.

**Comment by rmacgill** [comment]
Request is cached offline. Once we're displaying the current request for drivers, this will be done.

**Comment by woldegio** [comment]
Just looking through our remaining issues, this is finished now right?

**Comment by rmacgill** [comment]
Yeah, seems to work fine.
