### ISSUE TITLE
Incomplete Registration Break

### ISSUE THREAD

**Issue by hmp31** [CMPUT301W20T12/GufyGuber#93]
If the app is closed after signing into google and before completing registration as a rider or driver the app gets stuck in trying to sign into a non-existent user (user has to reinstall app to fix this currently).

**Comment by rmacgill** [comment]
Right. I remember that our workaround used to be to click on that extra sign-out button, but we've removed that now.

**Comment by hmp31** [comment]
Mhm, I think I have a decent fix for it. Seems to work for force-shutdowns as well.
